// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarWarsProject.Data;

#nullable disable

namespace StarWarsProject.Migrations
{
    [DbContext(typeof(StarWarsProjectContext))]
    [Migration("20221222121407_dataseed")]
    partial class dataseed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CharacterWeapon", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("WeaponsWeaponId")
                        .HasColumnType("int");

                    b.HasKey("CharacterId", "WeaponsWeaponId");

                    b.HasIndex("WeaponsWeaponId");

                    b.ToTable("CharacterWeapon");
                });

            modelBuilder.Entity("StarWarsProject.Models.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterId"), 1L, 1);

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.HasKey("CharacterId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("StarWarsProject.Models.CharacterStats", b =>
                {
                    b.Property<int>("CharacterStatsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterStatsId"), 1L, 1);

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("Force")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("strength")
                        .HasColumnType("int");

                    b.HasKey("CharacterStatsId");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.ToTable("CharacterStats");
                });

            modelBuilder.Entity("StarWarsProject.Models.Species", b =>
                {
                    b.Property<int>("SpeciesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpeciesId"), 1L, 1);

                    b.Property<string>("SpeciesName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpeciesId");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            SpeciesId = 1,
                            SpeciesName = "Human"
                        },
                        new
                        {
                            SpeciesId = 2,
                            SpeciesName = "Wookie"
                        },
                        new
                        {
                            SpeciesId = 3,
                            SpeciesName = "Jawa"
                        });
                });

            modelBuilder.Entity("StarWarsProject.Models.Weapon", b =>
                {
                    b.Property<int>("WeaponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeaponId"), 1L, 1);

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WeaponId");

                    b.ToTable("Weapons");

                    b.HasData(
                        new
                        {
                            WeaponId = 1,
                            Damage = 100,
                            Name = "Ligthsaber"
                        },
                        new
                        {
                            WeaponId = 2,
                            Damage = 30,
                            Name = "Blaster"
                        },
                        new
                        {
                            WeaponId = 3,
                            Damage = 20,
                            Name = "Blaster Pistol"
                        });
                });

            modelBuilder.Entity("CharacterWeapon", b =>
                {
                    b.HasOne("StarWarsProject.Models.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsProject.Models.Weapon", null)
                        .WithMany()
                        .HasForeignKey("WeaponsWeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StarWarsProject.Models.Character", b =>
                {
                    b.HasOne("StarWarsProject.Models.Species", "Species")
                        .WithMany("Character")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("StarWarsProject.Models.CharacterStats", b =>
                {
                    b.HasOne("StarWarsProject.Models.Character", "Character")
                        .WithOne("CharacterStats")
                        .HasForeignKey("StarWarsProject.Models.CharacterStats", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("StarWarsProject.Models.Character", b =>
                {
                    b.Navigation("CharacterStats")
                        .IsRequired();
                });

            modelBuilder.Entity("StarWarsProject.Models.Species", b =>
                {
                    b.Navigation("Character");
                });
#pragma warning restore 612, 618
        }
    }
}
